cors:
  spring:
    mvc:
      cors:
        allow-credentials: true
        allowed-headers: "*"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-origins: "http://localhost:4200"
